### ISSUE TITLE
请问你的程序编译之后怎么运行呢

### ISSUE THREAD

**Issue by peterwangx** [TianyiQ/Doudizhu-MCTS#1]
请问你的程序编译之后怎么运行呢？

**Comment by peterwangx** [comment]
能否给个测试用例

**Comment by TianyiQ** [comment]
这份代码是适配于 botzone 平台上的交互方式的，可参考 https://wiki.botzone.org.cn/index.php?title=FightTheLandlord2 。
测试用例的话，在 botzone 上随便找一局 FightTheLandlord2 游戏的历史对局，在随便一个时间点暂停，然后复制页面下方提供的输入内容和输出内容，就能得到一组测试用例。

**Comment by peterwangx** [comment]
好的👌多谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: TianyiQ ***@***.***&gt;
发送时间: 2022年1月6日 16:51
收件人: TianyiQ/Doudizhu-MCTS ***@***.***&gt;
抄送: peterwangx ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[TianyiQ/Doudizhu-MCTS] 请问你的程序编译之后怎么运行呢 (Issue #1)





 
这份代码是适配于 botzone 平台上的交互方式的，可参考 https://wiki.botzone.org.cn/index.php?title=FightTheLandlord2 。
 测试用例的话，在 botzone 上随便找一局 FightTheLandlord2 游戏的历史对局，在随便一个时间点暂停，然后复制页面下方提供的输入内容和输出内容，就能得到一组测试用例。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
