### ISSUE TITLE
请问我把tuning\simu1\full.cpp,以及mixed.cpp接入到botzone平台，对战时轮到 AI出牌，提示程序崩溃，而source\mian.cpp则能正常对战。请问是什么原因呢？

### ISSUE THREAD

**Issue by peterwangx** [TianyiQ/Doudizhu-MCTS#2]

**Comment by TianyiQ** [comment]
`full.cpp` 和 `mix.cpp` 从命令行参数来获取程序运行时的参数取值，而平台上不会给命令行参数，所以在平台上会崩溃。`main.cpp` 的参数取值硬编码在代码里，所以没有问题。

整个 `tuning` 目录下的东西都是用来调参的（而且代码文件可能并不是最新版本），不建议使用里面的代码作其他目的。`source` 目录下的 `main.cpp` 是调参后得到的最优结果。

**Comment by peterwangx** [comment]
多谢指点



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: TianyiQ ***@***.***&gt;
发送时间: 2022年1月7日 05:52
收件人: TianyiQ/Doudizhu-MCTS ***@***.***&gt;
抄送: peterwangx ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[TianyiQ/Doudizhu-MCTS] 请问我把tuning\simu1\full.cpp,以及mixed.cpp接入到botzone平台，对战时轮到 AI出牌，提示程序崩溃，而source\mian.cpp则能正常对战。请问是什么原因呢？ (Issue #2)





 
full.cpp 和 mix.cpp 从命令行参数来获取程序运行时的参数取值，而平台上不会给命令行参数，所以在平台上会崩溃。main.cpp 的参数取值硬编码在代码里，所以没有问题。
 
整个 tuning 目录下的东西都是用来调参的（而且代码文件可能并不是最新版本），不建议使用里面的代码作其他目的。source 目录下的 main.cpp 是调参后得到的最优结果。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
